### ISSUE TITLE
Copy page content as markdown into task description

### ISSUE THREAD

**Issue by oae** [chrschorn/one-click-ticktick#1]
Can you add an option to copy page content as a markdown into the task description? [This](https://github.com/deathau/markdownload) chrome extension can copy site content as markdown. Maybe it can be useful

**Comment by chrschorn** [comment]
Hi, thank you for the suggestion! I have no plans for this at the moment, but I can see how it would be very useful. A pull request would be more than welcome.

**Comment by chrschorn** [comment]
@oae Once 1.4.0 is live, this functionality will be there!
