### ISSUE TITLE
No Notification when sending a new page in Chrome

### ISSUE THREAD

**Issue by AndyLiu404** [chrschorn/one-click-ticktick#2]
The task was added to inbox indeed but didn't got notification to confirm it. 

I've turned on the option.

I was using latest Chrome
```
Chrome is up to date
Version 110.0.5481.100 (Official Build) (arm64)
```
<img width="1185" alt="Screenshot 2023-02-18 at 4 43 28 PM" src="https://user-images.githubusercontent.com/18258408/219905863-4cbcab19-ccca-4907-a72b-7f104c2625db.png">

and was sending a youtube link to TickTick: https://www.youtube.com/watch?v=SV2crCB-uw4
Also reproduced on other webpages

**Comment by chrschorn** [comment]
Hi, thanks for your feedback! 

Did you have any kind of "do not disturb" / focus mode activated on your OS? The extension uses your OS' notification system, so it will be impacted by these types of settings.

**Comment by chrschorn** [comment]
Stale / no response
