### ISSUE TITLE
Notifications stopped popping up for extension - windows 11

### ISSUE THREAD

**Issue by SamGu-NRX** [chrschorn/one-click-ticktick#8]
The chrome extension stopped popping up notifications when the button is clicked, although websites do register and appear in ticktick. I have made sure notifications is turned on for both my chrome browser and computer and it appears to be the extension's issue. I have also tried reinstalling the extension and turning on and off the option for notifications in settings but it does not seem to work. Using windows 11.

Also using latest version of chrome:
Version 119.0.6045.124

**Comment by SamGu-NRX** [comment]
I believe this is a great extension, but it seems like there is a consistent issue that appears on all webpages. @chrschorn

**Comment by chrschorn** [comment]
Hi @SamGu-NRX, I see you closed the issue. Are you still facing the notification problem?
